# Generated by Django 4.1.1 on 2022-10-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryColOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='gallery/img')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryColThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='gallery/img')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryColTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='gallery/img')),
            ],
        ),
    ]
