# Generated by Django 4.1.1 on 2022-10-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_achievement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
