# Generated by Django 4.1.1 on 2022-10-29 22:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
